//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMPEDA_V01.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Dosen
    {
        public Dosen()
        {
            this.Transaksis = new HashSet<Transaksi>();
        }
        
        [Required(ErrorMessage="Silakan lengkapi NIP Anda", AllowEmptyStrings=false)]
        public string NIP { get; set; }
        public int idJurusan { get; set; }
        [Required(ErrorMessage="Silakan masukkan password akun Anda", AllowEmptyStrings=false)]
        [DataType(System.ComponentModel.DataAnnotations.DataType.Password)]
        public string password_Dosen { get; set; }
        public string namaDosen { get; set; }
        public string teleponDosen { get; set; }
        public string alamatDosen { get; set; }
        public string emailDosen { get; set; }
        public Nullable<int> poinPunishmentDosen { get; set; }
        public string barcodeImageDosen { get; set; }
        public string barcodeDosen { get; set; }
        public string password_Dosen { get; set; }
    
        public virtual JurusanInstansi JurusanInstansi { get; set; }
        public virtual ICollection<Transaksi> Transaksis { get; set; }
    }
}
