//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMPEDA_V01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dosen
    {
        public Dosen()
        {
            this.Transaksis = new HashSet<Transaksi>();
        }
    
        public string NIP { get; set; }
        public int idJurusan { get; set; }
        public string namaDosen { get; set; }
        public string teleponDosen { get; set; }
        public string alamatDosen { get; set; }
        public string emailDosen { get; set; }
        public Nullable<int> poinPunishmentDosen { get; set; }
    
        public virtual JurusanInstansi JurusanInstansi { get; set; }
        public virtual ICollection<Transaksi> Transaksis { get; set; }
    }
}
