//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMPEDA_V01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JurusanInstansi
    {
        public JurusanInstansi()
        {
            this.Dosens = new HashSet<Dosen>();
            this.Mahasiswas = new HashSet<Mahasiswa>();
            this.Pegawais = new HashSet<Pegawai>();
        }
    
        public int idJurusan { get; set; }
        public string namaJurusan { get; set; }
        public string alamatJurusan { get; set; }
        public string teleponJurusan { get; set; }
    
        public virtual ICollection<Dosen> Dosens { get; set; }
        public virtual ICollection<Mahasiswa> Mahasiswas { get; set; }
        public virtual ICollection<Pegawai> Pegawais { get; set; }
    }
}
