//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMPEDA_V01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sepeda
    {
        public Sepeda()
        {
            this.Transaksis = new HashSet<Transaksi>();
        }
    
        public int idSepeda { get; set; }
        public int idShelter { get; set; }
        public string merkSepeda { get; set; }
        public string warnaSepeda { get; set; }
        public short ketersediaan { get; set; }
        public string keterangan { get; set; }
    
        public virtual Shelter Shelter { get; set; }
        public virtual ICollection<Transaksi> Transaksis { get; set; }
    }
}
