//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMPEDA_V01.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SimpedaEntities : DbContext
    {
        public SimpedaEntities()
            : base("name=SimpedaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dosen> Dosens { get; set; }
        public virtual DbSet<JurusanInstansi> JurusanInstansis { get; set; }
        public virtual DbSet<Mahasiswa> Mahasiswas { get; set; }
        public virtual DbSet<Pegawai> Pegawais { get; set; }
        public virtual DbSet<Sepeda> Sepedas { get; set; }
        public virtual DbSet<Shelter> Shelters { get; set; }
        public virtual DbSet<Transaksi> Transaksis { get; set; }
    
        public virtual ObjectResult<Nullable<int>> GetNewIdTransaction()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GetNewIdTransaction");
        }
    
        public virtual ObjectResult<string> GetLokasiShelter(Nullable<int> idShelter)
        {
            var idShelterParameter = idShelter.HasValue ?
                new ObjectParameter("idShelter", idShelter) :
                new ObjectParameter("idShelter", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetLokasiShelter", idShelterParameter);
        }
    
        public virtual ObjectResult<string> GetNamaShelter(Nullable<int> idShelter)
        {
            var idShelterParameter = idShelter.HasValue ?
                new ObjectParameter("idShelter", idShelter) :
                new ObjectParameter("idShelter", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetNamaShelter", idShelterParameter);
        }
    }
}
